### ISSUE TITLE
Can there be a stable/latest branch to follow?

### ISSUE THREAD

**Issue by ahayzen** [gmodena/nix-flatpak#113]
Disko have a branch that contains the latest stable release `github:nix-community/disko/latest`.

It would be nice to have similar for `nix-flatpak` as then I could use `github:gmodena/nix-flatpak/latest` in the `flake.nix`, have CI update the lock file and perform tests to ensure that things still work.

Currently I need to monitor this repo and manually update the git url to match the ref of a release.

**Comment by gmodena** [comment]
Hi @ahayzen,

Thanks for reaching out. I am not fond of the long-lived branches workflow, so I don't see a `stable` branch happening. However, I think what you're asking could be addressed by simply adding a `latest` tag that points to the most recent tagged commit. I am not familiar with disko, but I suppose that is what they are doing: [https://github.com/nix-community/disko/tags](https://github.com/nix-community/disko/tags).

If this does not break the flakeHub publication workflow, I see no problem with auto-tagging with `latest` on release.

**Comment by gmodena** [comment]
Took me some fiddling, but the tagging workflow is now automated.

https://github.com/gmodena/nix-flatpak/releases/tag/latest points to [8bdc254](https://github.com/gmodena/nix-flatpak/commit/8bdc2540da516006d07b04019eb57ae0781a04b3), the most recent commit tagged as [v0.5.2 ](https://github.com/gmodena/nix-flatpak/releases/tag/v0.5.2).

You can track the `latest` release with:
```
nix-flatpak.url = "github:gmodena/nix-flatpak/?ref=latest";
```

Or alternatively:
```
nix-flatpak.url = "github:gmodena/nix-flatpak/latest";
```

**Comment by ahayzen** [comment]
Awesome! Thank you for quickly adding this :-)
