### ISSUE TITLE
Provide nixos user service

### ISSUE THREAD

**Issue by SuperSandro2000** [gmodena/nix-flatpak#16]
I am not using home-manager and wanted to manage my flatpaks via systemd.user.

This shouldn't be to hard as we could just add the existing options to systemd.user and add new options or attr to change the installation method to user.

This probably only makes sense on single user system but I only have those.

This is what I hacked together:

```nix
options = {
  	services.flatpak = import (nix-flatpak + "/modules/options.nix") { inherit lib pkgs; };
};

config = {
  user = {
    services.flatpak-managed-install = {
      wants = [ "network-online.target" ];
      wantedBy = [ "multi-user.target" ];
      serviceConfig = {
        Type = "oneshot";
        ExecStart = import (nix-flatpak + "/modules/installer.nix") { inherit pkgs lib; cfg = config.services.flatpak; installation = "user"; };
      };
    };

    timers.flatpak-managed-install = {
      timerConfig = {
        Unit = "flatpak-managed-install";
        OnCalendar = config.services.flatpak.update.auto.onCalendar;
        Persistent = true;
      };
      wantedBy = [ "timers.target" ];
    };
  };
};
```

**Comment by gmodena** [comment]
> I am not using home-manager and wanted to manage my flatpaks via systemd.user.

Maybe I need to go read some doc, but wouldn't  `systemd.user.services` enable the unit for _all_ users? If so it might be ok for your use case, but would break multi-user setups.
