### ISSUE TITLE
Question regarding scope

### ISSUE THREAD

**Issue by 573** [gmodena/nix-flatpak#20]
Would this work on non-NixOS systems with just home-manager as well  or is the home-manager module just for managing the flatpaks themselves ?

**Comment by gmodena** [comment]
Hey @573,

While the module supports standalone home-manager install (available in `main`), I don't test on non-nixos targets right now. 

I would love to support other linux distros, but those are considered out of scope for the time being.

I'm not familiar with targets other than nixos (and darwin), so can't make guarantees; but if a non nixos target can run home-manager declared systemd units, it should be trivial to adjust the module to make it work there.

Also, the installer script builds on ${pkgs.flatpak}. Target hosts should have the capability to install that package.
