### ISSUE TITLE
nix-flatpak "stopped working"

### ISSUE THREAD

**Issue by jh-devv** [gmodena/nix-flatpak#43]
Hey!

Recently, I added the nix-flatpak flake to my NixOS flake!

Though, it first worked fine, but now it does not seems to do anything when reloading the config.

Maybe related: #26

**Comment by ReedClanton** [comment]
Don't know if I'll be able to help, but if I am, I'll need more details.

**Comment by jh-devv** [comment]
> Don't know if I'll be able to help, but if I am, I'll need more details.

Yea, sorry for an vague PR, seems to be related to some HM import stuff and infinite recursion...

**Comment by gmodena** [comment]
There's an example on how to import `nix-flatpak` in HM (installed as nixos module) at: https://github.com/gmodena/nix-flatpak/blob/main/testing-base/flake.nix#L23

Hope this helps. Infinite recursion issues can be a pain to troubleshoot. Feel free to paste a stack trace (build --show-trace).
