### ISSUE TITLE
Failed to connect to bus: No medium found

### ISSUE THREAD

**Issue by jh-devv** [gmodena/nix-flatpak#65]
First, I want to say, it installs the flatpaks completely fine?
According to `systemctl status flatpak-managed-install.service --user` it seems to be working:
```log
Apr 08 13:45:27 luminara systemd[2150]: Starting flatpak-managed-install.service...
Apr 08 13:45:27 luminara xs6c8vpw51jb6winrck4s48mxp53m1hp-flatpak-managed-install[115860]: Skippi>
Apr 08 13:45:27 luminara xs6c8vpw51jb6winrck4s48mxp53m1hp-flatpak-managed-install[115865]: Skippi>
Apr 08 13:45:27 luminara xs6c8vpw51jb6winrck4s48mxp53m1hp-flatpak-managed-install[115872]: Skippi>
Apr 08 13:45:27 luminara xs6c8vpw51jb6winrck4s48mxp53m1hp-flatpak-managed-install[115877]: Skippi>
Apr 08 13:45:27 luminara systemd[2150]: Finished flatpak-managed-install.service.
```
`journalctl -f` and `dbus-monitor` shows this and more:
```
systemd1; interface=org.freedesktop.systemd1.Manager; member=JobNew
   uint32 980
   object path "/org/freedesktop/systemd1/job/980"
   string "flatpak-managed-install.service"
```
It seems *it's is* connecting to the bus, the error in the `home manager switch` logs does not seem to matter?
```
Failed to connect to bus: No medium found
```

**Metadata**

```console
[jh-devv@luminara:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.4, NixOS, 24.05 (Uakari), 24.05.20240406.ff0dbd9`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - nixpkgs: `/nix/store/j10523yhkcc34478azkgcl70yzcx6j2j-source`
```

**Comment by jh-devv** [comment]
https://github.com/NixOS/nixpkgs/issues/183629

**Comment by gmodena** [comment]
I'm closing this issue since it seems hyperland + system config related:
https://github.com/gmodena/nix-flatpak/pull/66#issuecomment-2094350411

Please do feel free to reopen, or follow up in a Discussions thread if needed.

**Comment by jh-devv** [comment]
> I'm closing this issue since it seems hyperland + system config related:
> https://github.com/gmodena/nix-flatpak/pull/66#issuecomment-2094350411
> 
> Please do feel free to reopen, or follow up in a Discussions thread if needed.

Year, I switched to Cosmic and the issue is gone :3
