### ISSUE TITLE
Existing Flatpaks

### ISSUE THREAD

**Issue by C4E5G3** [gmodena/nix-flatpak#68]
Sorry - seems to be an issue with updates.

**Comment by gmodena** [comment]
Can you define "meltdown" ?

You don't need to uninstall flatpkas for this module to work. From the README:

_By default nix-flatpak will only manage (install/uninstall/update) packages declared in the `services.flatpak.packages` and repositories declared in `services.flatpak.remotes`. Flatpak packages and repositories installed by the command line or app stores won't be affected.

Set `services.flatpak.uninstallUnmanaged = true` to alter this behaviour, and have nix-flatpak manage the lifecycle of all flatpaks packages and repositories._

Beware though that  depending on how you setup nix-flatpak (nixos vs home-manager), and how you install packages from cli (system vs user), you might end with duplicate installed packages.

**Comment by gmodena** [comment]
no worries @C4E5G3 ! Glad it is fixed. Feel free to re-open, if it turns out to be an issue related with nix-flatpak.
