### ISSUE TITLE
How to pass arguments to app

### ISSUE THREAD

**Issue by Axolord** [gmodena/nix-flatpak#70]
Hi, I found that electron based apps (and chromium derivatives itself) need to be run with extra arguments to start in a wayland session. So for ungoogled chromium I need to run `flatpak run io.github.ungoogled_software.ungoogled_chromium --ozone-platform-hint=auto` to have proper scaling and such.

Is there a way to add this argument declarative? 

Thanks!

**Comment by gmodena** [comment]
Hi @Axolord . `nix-flatpak` does not provide a wrapper for `flatpak run` or any launcher scripts. You can customize application requirements with  `services.flatkpatk.overrides` (it wraps [flatpak override](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-override), but not parametrize `run`.

For you use case, did you consider aliasing  `ungoogled_chromium` in your shell config? Or maybe having a script with the desired `flatpak run` command params. 

Either way, you should be able to do it declaratively with Nix. The specific method is somewhat system-dependent; on NixOS, you could use [shellAlias](https://search.nixos.org/options?channel=24.05&show=programs.bash.shellAliases&from=0&size=50&sort=relevance&type=packages&query=shellAliases).
