### ISSUE TITLE
Fix "uninstallUnamanged" typo to "uninstallUnmanaged"

### ISSUE THREAD

**Issue by lighterly** [gmodena/nix-flatpak#73]
Hi @gmodena, I think you should fix this. Why? Because someone might struggle trying to find out what's wrong until they realize that the variable is actually misspelled. Also, thank you very much for this useful package you made!

https://github.com/gmodena/nix-flatpak/blob/45bf66f7068db79b552da864c0e87452be624d6c/modules/options.nix#L172
https://github.com/gmodena/nix-flatpak/blob/45bf66f7068db79b552da864c0e87452be624d6c/modules/nixos.nix#L4
https://github.com/gmodena/nix-flatpak/blob/45bf66f7068db79b552da864c0e87452be624d6c/modules/home-manager.nix#L4

**Comment by gmodena** [comment]
Good catch! Thanks for reporting this bug.
