### ISSUE TITLE
flatpak uninstall --unused

### ISSUE THREAD

**Issue by m3thm4th** [gmodena/nix-flatpak#96]
Is it possible to run an equivalent to
`flatpak uninstall --unused --noninteractive --assumeyes` or `flatpak uninstall --unused -y`
declaratively right after periodic autoupdates to clean storage?

**Comment by gmodena** [comment]
Yes, that would be useful.

While this feature is not currently supported, it should be straightforward to implement. I wouldn’t enable it by default, but this cleanup could be performed when users set `services.flatpak.uninstallUnmanaged=true`.
